def pytest_configure():
    from django.conf import settings
    settings.configure(
        DEBUG_PROPAGATE_EXCEPTIONS=True,
        ROOT_URLCONF='thing',
        SSO_PROXY_LOGIN_URL='http://login.com',
        SSO_PROXY_SIGNUP_URL='http://signup.com',
        SSO_PROXY_LOGOUT_URL='http://logout.com',
        SSO_PROFILE_URL='http://profile.com',
        GREAT_HOME='http://home.com',
        GREAT_EXPORT_HOME='http://export.com',
        EXPORTING_NEW='http://export.com/new',
        EXPORTING_OCCASIONAL='http://export.com/occasional',
        EXPORTING_REGULAR='http://export.com/regular',
        GUIDANCE_MARKET_RESEARCH='http://market-research.com',
        GUIDANCE_CUSTOMER_INSIGHT='http://customer-insight.com',
        GUIDANCE_FINANCE='http://finance.com',
        GUIDANCE_BUSINESS_PLANNING='http://business-planning.com',
        GUIDANCE_GETTING_PAID='http://getting-paid.com',
        GUIDANCE_OPERATIONS_AND_COMPLIANCE='http://operations-and-compliance.com',
        SERVICES_FAB='http://export.com/fab',
        SERVICES_SOO='http://export.com/soo',
        SERVICES_EXOPPS='http://export.com/exopps',
        SERVICES_GET_FINANCE='http://export.com/get-finance',
        SERVICES_EVENTS='http://export.com/events',
        INFO_ABOUT='http://about.com',
        INFO_CONTACT_US='http://contact.com',
        INFO_PRIVACY_AND_COOKIES='http://privacy-and-cookies.com',
        INFO_TERMS_AND_CONDITIONS='http://terms-and-conditions.com',
        INFO_DIT='http://dit.com',
        INSTALLED_APPS=[
            'directory_constants',
            'directory_header_footer',
        ],
        HEADER_FOOTER_CONTACT_US_URL='http://contact-us.com',
        TEMPLATES=[{
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'APP_DIRS': True,
        }],
        HEADER_FOOTER_CSS_ACTIVE_CLASSES={'fab': True},
    )
